---
- name: Configure neutron-api server
  hosts: neutron-api
  sudo: True
  gather_facts: True
  tags:
    - openstack
  vars:
    component: neutron
    subcomponent: server
    packages:
      - "{{ component }}-{{ subcomponent }}"
    services:
      - "{{ component }}-{{ subcomponent }}"
    config_files:
      - "{{ component }}.conf"
      - api-paste.ini

  tasks:

    - name: ensure {{ component }}-{{ subcomponent }} packages are installed
      apt: 
        pkg: "{{ item }}"
        state: latest 
        force: yes
        update_cache: yes 
        cache_valid_time: 600
      with_items: packages

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: services

    - name: ensure {{ component }} sqlite is deleted
      file: 
        dest: /var/lib/{{ component }}/{{ component }}.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/{{ component }}/{{ item }}
        dest: /etc/{{ component }}/{{ item }}
        owner: root
        group: "{{ component }}"
        mode: 0640
      with_items: config_files

    - name: make sure symlink to ovs_neutron_plugin.ini exists
      file: 
        src: /etc/neutron/plugins/ml2/ml2_conf.ini
        dest: /etc/neutron/plugin.ini
        state: link

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: services

    - name: wait for neutron to come back up
      wait_for:
        host: "{{ neutron_endpoint_host }}"
        port: 9696
