---
- name: setup steps that are not specific to a particular role or project
  hosts: openstack-hosts
  sudo: True
  gather_facts: True
  tags:
    - openstack
  tasks:
    - name: use juno
      # Ansible 1.7 does not support cloud-archive:juno format https://github.com/ansible/ansible-modules-core/issues/292
      apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/juno main'
      
    - name: print system information
      debug: 
        msg: System {{ inventory_hostname }} has ipv4 addresses {{ ansible_all_ipv4_addresses }}

    - name: ensure required base packages are present
      apt: 
        pkg: "{{ item }}" 
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - chrony
        - python-mysqldb
        - python-software-properties

    - name: ensure chrony server is stopped
      service: 
        name: chrony
        state: stopped

    - name: install chrony.conf 
      template: 
        src: templates/etc/chrony/chrony.conf 
        dest: /etc/chrony/chrony.conf 
        owner: root 
        group: root 
        mode: 0644

    - name: set clocks to public ntp server
      command: ntpdate {{ external_ntp_host }}
      ignore_errors: yes
      register: ntpdate_result
      until: ntpdate_result|success
      retries: 5
      delay: 5

    - name: make sure chrony server is started and enabled
      service: 
        name: chrony
        state: restarted 
        enabled: yes
      when: "'ntpserver' in group_names"

    - name: set clocks to local chrony server
      command: ntpdate {{ ntp_host }}
      register: ntpdate_result
      when: "'ntpserver' not in group_names"
      until: ntpdate_result|success
      retries: 5
      delay: 5

    - name: save system clock to hardware
      command: hwclock --systohc

    - name: make sure chrony is started and enabled everywhere
      service: 
        name: chrony
        state: restarted 
        enabled: yes
